### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [ItsMax123/KOTH#1]
I know the plugin its not finished, im just suggesting you can do it whenever you want
![image](https://user-images.githubusercontent.com/89011093/135902620-b221bfee-8adc-4163-aee9-b863f7876536.png)
Is a discord webhook which shows the coords of the KoTH, the world and the time

**Comment by ItsMax123** [comment]
Sure I can do that. Since you are the first person to contact me about this plugin, do you think I should support for multiple koth arenas?

**Comment by ghost** [comment]
> Sure I can do that. Since you are the first person to contact me about this plugin, do you think I should support for multiple koth arenas?

Yes, since the general purpose of a KoTH plugin is for HCF and UHCF servers and the average HCF or UHCF map has at least two KoTH i think it is needed.

**Comment by ItsMax123** [comment]
Discord webhooks added in: 51ba4c03a613d9a8643d3bfdfaf44faee1a52e88
