### ISSUE TITLE
Failed to load config /home/container/plugin_data/KOTH/data.yml: Expected array for base type, but got null" (EXCEPTION) in "pmsrc/src/utils/Config" at line 205

### ISSUE THREAD

**Issue by Auslatos** [ItsMax123/KOTH#5]
[21:13:07.838] [Server thread/CRITICAL]: pocketmine\utils\ConfigLoadException: "Failed to load config /home/container/plugin_data/KOTH/data.yml: Expected array for base type, but got null" (EXCEPTION) in "pmsrc/src/utils/Config" at line 205
--- Stack trace ---
  #0 pmsrc/src/utils/Config(121): pocketmine\utils\Config->load(string[41] /home/container/plugin_data/KOTH/data.yml, integer 2, array[0])
  #1 plugins/KOTH-master/src/Max/koth/KOTH(52): pocketmine\utils\Config->__construct(string[41] /home/container/plugin_data/KOTH/data.yml, integer 2)
  #2 pmsrc/src/plugin/PluginBase(137): Max\koth\KOTH->onEnable()
  #3 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #4 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object Max\koth\KOTH#29504)
  #5 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24911)
  #6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #7 pmsrc/src/PocketMine(327): pocketmine\server()
  #8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by Driwen** [comment]
same thing
